CREATE TABLE "GCG_5235_RFID_OUTPUT"(
 "EPC" CHAR(50) NOT NULL,
 "TID" CHAR(50),
 "USER_RFID" CHAR(16),
 "ANTENNA" CHAR(20) NOT NULL,
 "PEAKRSSI" CHAR(50),
 "DATEANDTIME" DATETIME,
 "READERNAME" CHAR(20) NOT NULL,
 "STARTEVENT" CHAR(50),
 "COUNT1" CHAR(50),
 "TAGEVENT" CHAR(50),
 "PROCESSED" CHAR(1),
 "TRANS_TYPE" CHAR(3),
 "WIRELESS_ID" CHAR(9) );
